### ISSUE TITLE
Final Project Proposal Submission

### ISSUE THREAD

**Issue by alanshen21** [QMSS-G5063-2022/Group_D_Changes_in_the_Video_Game_Landscape#1]
@QMSS-G5063-2022/teaching_team SHA:d96b948de011fd3404a7b5ce0de9bb4119253f0b

**Comment by Abhimanyu210100** [comment]
I noticed that the proposal mentions finding if covid had an impact on the gaming industry. However, the data mentioned in the proposal only shows user data that was collected during covid-19. In order to get a stronger analysis, you can try looking for a dataset from pre covid times.
